name: 'Get Issue Info'

on:
  issues: 
    types: 
      - opened
      - edited

jobs:
  get-issue-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Issue Info
        id: get-issue-info
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Use a API do GitHub para obter informações da issue
            const { data } = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            // Exemplo de captura de informações da issue
            const issueTitle = data.title;
            const issueBody = data.body;
            
            console.log(typeof issueBody);
            const joinBody = issueBody.replace(/[\r\n]+/g, '');

            // Defina as variáveis de saída para uso posterior
            core.setOutput('issueTitle', issueTitle);
            core.setOutput('joinBody', joinBody);
            
        
      - name: Use Issue Info
        id: issue-use
        run: |
          echo "Título da issue: ${{ steps.get-issue-info.outputs.issueTitle }}"
          echo "Corpo da issue: ${{ steps.get-issue-info.outputs.joinBody }}"