name: 'Get Issue Info'

on:
  issues: 
    types: 
      - opened
      - edited

jobs:
  get-issue-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Issue Info
        id: get-issue-info
        uses: actions/github-script@v4
        with:
          script: |
            const { data } = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
              issueTitle: context.issue.txt_api_key_dev
              txt_api_key_dev: context.issue.txt_api_key_dev
            });
          
            
            // Defina as variáveis de saída para uso posterior
            console.log(`owner=${data.issueTitle}`);
            console.log(`repo=${data.issueTitle}`);
            console.log(`issue_number=${data.issue_number}`);
            console.log(`issueTitle=${data.issueTitle}`);
            console.log(`txt_api_key_dev=${data.txt_api_key_dev}`);
        
      - name: Use Issue Info
        id: issue-use
        run: |
          echo "Título da issue: ${{ steps.get-issue-info.outputs.issueTitle }}"
          echo "Corpo da issue: ${{ steps.get-issue-info.outputs.issueBody }}"
        
          