name: 'Testing my Consumers'

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-consumers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Run Test
        run: node ./test/script/main.js